name: CI/CD

# Chạy pipeline mỗi khi có push lên main hoặc PR vào main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: everfit/devops-test

jobs:
  test:
    name: Run Tests with Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Run tests
        run: |
          cd devops-app
          docker compose run --rm app poetry install --no-root
          docker compose run --rm app poetry run pytest -v

  build-and-push:
    name: Build and Push Docker Image to ECR
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::810610046256:role/GitHubOIDCDeployRole
          aws-region: ap-southeast-1 
  
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Build and Push Docker Image to ECR
        env:
          ECR_REGISTRY: 810610046256.dkr.ecr.ap-southeast-1.amazonaws.com
          ECR_REPOSITORY: test
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd devops-app
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
  deploy:
    name: Deploy to Amazon ECS
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::810610046256:role/GitHubOIDCDeployRole
          aws-region: ap-southeast-1
  
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster devops-app-cluster \
            --service devops-app-service \
            --force-new-deployment

